### ISSUE TITLE
Invalid Value In Cast When Reading TSG Files

### ISSUE THREAD

**Issue by AryaGeramiZadegan** [FractalGeoAnalytics/pytsg#7]
When attempting to read TSG files I get a runtime warning. I'm not sure if this is noteworthy as I haven't tried doing much with the data as of yet. TSG itself has no trouble reading the files so I assume that means that they are valid.

Replication:
```python
from pytsg import parse_tsg
tsg_package_path = '<insert path of dir with TSG files here>'
data = parse_tsg.read_package(tsg_package_path)
```

Resulting Error:
```
RuntimeWarning: invalid value encountered in cast
  bv = band_value.astype(int)
```

It might be worth noting that `data.tir.scalars` has many columns zeroed out including:
FeatExMethod, NumFeats, as well as all the Depth, Width, and Centre columns

**Comment by BenFGA** [comment]
@AryaGeramiZadegan sorry for the very late reply I didn't notice this come through. Do you have an example of the offending file that you could share?
