### ISSUE TITLE
extract_chips resulting in 'tjCompress2(): Invalid argument' error

### ISSUE THREAD

**Issue by GeoCass** [FractalGeoAnalytics/pytsg#8]
Hello, 
When attempting read and extract the cras files I get an error:

Code Replication: 
```
from pytsg import parse_tsg
from pytsg.parse_tsg import read_tsg_bip_pair,extract_chips
from pathlib import Path

inputfolder = Path('C:/Users/235027/Downloads/HyLogger/HDD-006')
cras_file = inputfolder.joinpath('292943_HDD-006_tsg_cras.bip')

data = parse_tsg.read_package(inputfolder, read_cras_file=True, extract_cras=True)
```

Error:
```
ValueError                                Traceback (most recent call last)
c:\Users\235027\Downloads\Apresentação\Espectros\Espectros.ipynb Cell 41 in <cell line: 8>()
      [5](vscode-notebook-cell:/c%3A/Users/235027/Downloads/Apresenta%C3%A7%C3%A3o/Espectros/Espectros.ipynb#Y104sZmlsZQ%3D%3D?line=4) inputfolder = Path('C:/Users/235027/Downloads/HyLogger/HDD-006')
      [6](vscode-notebook-cell:/c%3A/Users/235027/Downloads/Apresenta%C3%A7%C3%A3o/Espectros/Espectros.ipynb#Y104sZmlsZQ%3D%3D?line=5) cras_file = inputfolder.joinpath('292943_HDD-006_tsg_cras.bip')
----> [8](vscode-notebook-cell:/c%3A/Users/235027/Downloads/Apresenta%C3%A7%C3%A3o/Espectros/Espectros.ipynb#Y104sZmlsZQ%3D%3D?line=7) data = parse_tsg.read_package(inputfolder, read_cras_file=True, extract_cras=True)

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytsg\parse_tsg.py:1016, in read_package(foldername, read_cras_file, extract_cras, imageoutput)
   1013     if not imageoutput.exists():
   1014         imageoutput.mkdir()
-> 1016     extract_chips(file_pairs.cras, imageoutput, nir)
   1017     cras = Cras
   1018 else:

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pytsg\parse_tsg.py:597, in extract_chips(filename, outfolder, spectra)
    595 tmp_file = "{}.jpg".format(cursample)
    596 outfile = outfolder.joinpath(tmp_file)
--> 597 outjpg = encode_jpeg(current_image)
    598 with open(outfile, "wb") as tmpf:
    599     tmpf.write(outjpg)

File simplejpeg/_jpeg.pyx:474, in simplejpeg._jpeg.encode_jpeg()

ValueError: tjCompress2(): Invalid argument
```

This code results in the 125 clippings that make up the first column of the Tray0001 samples, and then gives the error.

I have already tried importing the data separately with 'read_tsg_bip_pair' and applying the 'extract_chips(cras_file, image_folder, data.nir)' code, but gives me the same result/error. 

What could I be doing wrong?
Thanks!

**Comment by BenFGA** [comment]
@GeoCass sorry I took so long to reply I've not worked out how to get notified when someone puts an issue in.

It seems like the cras file is corrupted, you can try opening it in the free tsg viewer which should at least confirm if the file is openable.

**Comment by BenFGA** [comment]
I assume that the below code fails as well with the same error.

``` python 
from pytsg import parse_tsg
from pytsg.parse_tsg import read_tsg_bip_pair,extract_chips
from pathlib import Path

inputfolder = Path('C:/Users/235027/Downloads/HyLogger/HDD-006')
cras_file = inputfolder.joinpath('292943_HDD-006_tsg_cras.bip')
cras = parse_tsg.read_cras(cras_file)

```

**Comment by GeoCass** [comment]
Hello, thanks for taking a look at the issue!

I have tried with another TSG file (drillhole HDD-046) and unfortunately gave me the same result. For now I'm unable to test it using the free TSG viewer, but I'll take a look as soon as possible.


---

> I assume that the below code fails as well with the same error.
> 
> ```python
> from pytsg import parse_tsg
> from pytsg.parse_tsg import read_tsg_bip_pair,extract_chips
> from pathlib import Path
> 
> inputfolder = Path('C:/Users/235027/Downloads/HyLogger/HDD-006')
> cras_file = inputfolder.joinpath('292943_HDD-006_tsg_cras.bip')
> cras = parse_tsg.read_cras(cras_file)
> ```

The code above actually worked for both drillholes, or at least it didn't produce any errors

**Comment by BenFGA** [comment]
are those both diamond drill holes? if so extract chips won't work, because the structure of chip mode files and diamond files is slightly different. 

Have you tried https://github.com/CSIRO-GeoscienceAnalytics/tsg-xr it deals with some of the issues around aligning spectra to imagery.

**Comment by GeoCass** [comment]
@BenFGA oh, so that's it, both of them are diamond drill holes indeed. 
I will try this library you recommended, thank you again!
